///|
pub const README_ICON = "/readme.svg"

///|
pub const TYPE_ICON = "/type.svg"

///|
pub const TYPE_ALIAS_ICON = "/code-brackets.svg"

///|
pub const VALUE_ICON = "/code-brackets.svg"

///|
pub const TRAIT_ICON = "/components.svg"

///|
pub const FOLDER_OPEN = "/folder-open.svg"

///|
pub const FOLDER_CLOSE = "/folder-close.svg"

///|
pub let icon_close = "/close.svg"

///|
pub const SECTION_OPEN = "/section-open.svg"

///|
pub const SECTION_CLOSE = "/section-close.svg"

///|
pub const EXPANSION = "/expansion.svg"

///|
pub const REDUCTION = "/reduction.svg"

///|
pub const FILTER = "/filter.svg"

///|
pub const SEARCH = "/search.svg"

///|
pub const SHARE = "/share.svg"

///|
pub let ok = "/ok.svg"

///|
pub let clipboard = "/clipboard.svg"

///|
pub let tag = "/tag.svg"

///|
pub let user = "/user.svg"

///|
pub let install = "/install.svg"

///|
pub let license = "/license.svg"

///|
pub let repo = "/repo.svg"

///|
pub let code = "/code.svg"

///|
pub let terminal = "/terminal.svg"

///|
pub let deps = "/deps.svg"

///|
pub let book_open = "/book-open.svg"

///|
pub const SUN_ICON = "/sun.svg"

///|
pub const MOON_ICON = "/moon.svg"

///|
pub const HAMBURGER_BUTTON = "/hamburger-button.svg"

///|
pub const LOGO = "/mooncake-pic.png"

///|
pub let dead_rabbit =
  #|         --  --
  #|       /  //  / __--------_
  #|      /  //  /_/            \
  #|   ---      -                \ __
  #|  / X        /        ____   /   )
  #|  *_________/__/_____/______/ `--

///|
pub let builtins_package_path : Map[String, String] = {
  "Bool": "core/bool",
  "Byte": "core/byte",
  "Bytes": "core/bytes",
  "Char": "core/char",
  "Double": "core/double",
  "FixedArray": "core/array",
  "Array": "core/array",
  "Float": "core/float",
  "Int": "core/int",
  "Int16": "core/int16",
  "Int64": "core/int64",
  "String": "core/string",
  "UInt": "core/uint",
}
