///|
pub const URL_BASE = "http://127.0.0.1:3000"

///|
pub const README_ICON = "/readme.svg"

///|
pub const TYPE_ICON = "/type.svg"

///|
pub const TYPE_ALIAS_ICON = "/code-brackets.svg"

///|
pub const VALUE_ICON = "/code-brackets.svg"

///|
pub const TRAIT_ICON = "/components.svg"

///|
pub const FOLDER_OPEN = "/folder-open.svg"

///|
pub const FOLDER_CLOSE = "/folder-close.svg"

///|
pub const SECTION_OPEN = "/section-open.svg"

///|
pub const SECTION_CLOSE = "/section-close.svg"

///|
pub const EXPANSION = "/expansion.svg"

///|
pub const REDUCTION = "/reduction.svg"

///|
pub const FILTER = "/filter.svg"

///|
pub const SEARCH = "/search.svg"

///|
pub const SHARE = "/share.svg"

///|
pub const LOGO = "/mooncake-pic.png"
