// Copyright 2025 International Digital Economy Academy
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
using @html {
  type Html,
  div,
  text,
  h1,
  p,
  pre,
  code,
  span,
  nothing,
  a,
  h3,
  ul,
  img,
  button,
}

///|
using @tea {type Cmd, batch, none}

///|
using @immut/sorted_map {type SortedMap}

///|
using @immut/sorted_set {type SortedSet}

///|
using @util {type Lazy, type Status}
